import {
  AirVent,
  ArrowUpFromLine,
  Bath,
  Bed,
  BedDouble,
  Bike,
  Camera,
  CircleCheck,
  CookingPot,
  Dices,
  Droplet,
  Droplets,
  Dumbbell,
  Expand,
  FileCheck,
  Flame,
  Fuel,
  HandCoins,
  type LucideIcon,
  Microwave,
  PersonStanding,
  PlugZap,
  Presentation,
  Receipt,
  Refrigerator,
  ShoppingBag,
  ShoppingBasket,
  ShowerHead,
  Sparkles,
  SquareParking,
  Sun,
  Ticket,
  Tv,
  UserRound,
  UtensilsCrossed,
  Wifi,
  Zap,
} from 'lucide-react'

// Picks a meaningful line icon for a feature from its name (Airbnb-style amenity
// icons), so "Fuel" shows a fuel pump and "Linens" a bed — not the same tick on
// every row. First match wins; unknown features get a neutral check.
const RULES: [RegExp, LucideIcon][] = [
  [/kitchen|utensil|cooking/i, CookingPot],
  [/cutlery/i, UtensilsCrossed],
  [/bath/i, Bath], // bath, bathroom, bath tub
  [/geyser|shower/i, ShowerHead],
  [/\bac\b|air ?con/i, AirVent],
  [/fridge/i, Refrigerator],
  [/microwave/i, Microwave],
  [/fuel|diesel|petrol/i, Fuel],
  [/sleeps|berth/i, BedDouble],
  [/linen|blanket|pillow|bedding/i, Bed],
  [/allowance/i, HandCoins],
  [/driver|helper|staff|chauffeur/i, UserRound],
  [/toiletr/i, Droplets],
  [/clean/i, Sparkles],
  [/lpg|\bgas\b|bonfire|barbe?c?que|bbq/i, Flame],
  [/toll/i, Ticket],
  [/parking/i, SquareParking],
  [/tax|gst/i, Receipt],
  [/permit|permission/i, FileCheck],
  [/generator/i, Zap],
  [/power|electric/i, PlugZap],
  [/water/i, Droplet],
  [/grocer/i, ShoppingBasket],
  [/sightseeing/i, Camera],
  [/shopping/i, ShoppingBag],
  [/stage/i, Presentation],
  [/expand|deck/i, Expand],
  [/lift|roof/i, ArrowUpFromLine],
  [/terrace|solar/i, Sun],
  [/badminton|sport|gym/i, Dumbbell],
  [/yoga/i, PersonStanding],
  [/carrom|board game|games/i, Dices],
  [/\btv\b|television/i, Tv],
  [/wi-?fi|internet/i, Wifi],
  [/bike|cycle/i, Bike],
]

export function featureIcon(name: string): LucideIcon {
  return RULES.find(([pattern]) => pattern.test(name))?.[1] ?? CircleCheck
}
