/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    features: Feature;
    'caravan-filter-options': CaravanFilterOption;
    'tour-filter-options': TourFilterOption;
    'blog-categories': BlogCategory;
    caravans: Caravan;
    tours: Tour;
    galleries: Gallery;
    'blog-articles': BlogArticle;
    reviews: Review;
    'hero-slides': HeroSlide;
    tips: Tip;
    enquiries: Enquiry;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'caravan-filter-options': CaravanFilterOptionsSelect<false> | CaravanFilterOptionsSelect<true>;
    'tour-filter-options': TourFilterOptionsSelect<false> | TourFilterOptionsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    caravans: CaravansSelect<false> | CaravansSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'blog-articles': BlogArticlesSelect<false> | BlogArticlesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    tips: TipsSelect<false> | TipsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  name: string;
  /**
   * Icon shown next to this feature on the site.
   */
  icon: number | Media;
  category: 'spec' | 'inclusion' | 'exclusion' | 'unique-feature' | 'add-on';
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravan-filter-options".
 */
export interface CaravanFilterOption {
  id: number;
  /**
   * e.g. "Delhi", "Chauffeur Driven", "8–12 Berth", "Zenith".
   */
  name: string;
  group: 'base-location' | 'drive-type' | 'berth-range' | 'class';
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-filter-options".
 */
export interface TourFilterOption {
  id: number;
  /**
   * e.g. "Ladakh", "7–15 Days", "Riverside Caravanning".
   */
  name: string;
  group: 'duration-band' | 'location' | 'preference';
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravans".
 */
export interface Caravan {
  id: number;
  name: string;
  /**
   * URL path. Auto-filled from the title if left blank.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Used on cards.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "4–6 People".
   */
  sleeps?: string | null;
  /**
   * e.g. "Charges Start From Delhi".
   */
  chargesFrom?: string | null;
  /**
   * e.g. "Tata 4300 wb Chassis".
   */
  baseVehicle?: string | null;
  baseLocation?: (number | null) | CaravanFilterOption;
  driveType?: (number | null) | CaravanFilterOption;
  berthRange?: (number | null) | CaravanFilterOption;
  class?: (number | null) | CaravanFilterOption;
  specifications?: (number | Feature)[] | null;
  /**
   * Anything not in the tick-list above (free text).
   */
  additionalSpecifications?: string | null;
  uniqueFeatures?: (number | Feature)[] | null;
  /**
   * Anything not in the tick-list above (free text).
   */
  additionalUniqueFeatures?: string | null;
  inclusions?: (number | Feature)[] | null;
  /**
   * Anything not in the tick-list above (free text).
   */
  additionalInclusions?: string | null;
  exclusions?: (number | Feature)[] | null;
  /**
   * Anything not in the tick-list above (free text).
   */
  additionalExclusions?: string | null;
  addOns?: (number | Feature)[] | null;
  /**
   * Anything not in the tick-list above (free text).
   */
  additionalAddOns?: string | null;
  highlights?:
    | {
        /**
         * e.g. "Walk Through".
         */
        label: string;
        thumbnail?: (number | null) | Media;
        /**
         * YouTube link or short clip URL.
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  name: string;
  /**
   * URL path. Auto-filled from the title if left blank.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Used on cards.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the card, e.g. "15 Days".
   */
  durationLabel?: string | null;
  durationBand?: (number | null) | TourFilterOption;
  /**
   * e.g. "Delhi – Ladakh – Delhi".
   */
  routeLabel?: string | null;
  location?: (number | null) | TourFilterOption;
  preference?: (number | TourFilterOption)[] | null;
  /**
   * e.g. "May – September".
   */
  season?: string | null;
  itinerary?:
    | {
        /**
         * e.g. "Day 1: Delhi → Corbett".
         */
        dayTitle: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        /**
         * e.g. "Fun Activities".
         */
        label: string;
        thumbnail?: (number | null) | Media;
        /**
         * YouTube link or short clip URL.
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  tales?: (number | null) | BlogArticle;
  snaps?: (number | null) | Gallery;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles".
 */
export interface BlogArticle {
  id: number;
  title: string;
  /**
   * URL path. Auto-filled from the title if left blank.
   */
  slug: string;
  coverImage?: (number | null) | Media;
  /**
   * Short summary for cards.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The "Featuring" tags for this article.
   */
  category?: (number | BlogCategory)[] | null;
  /**
   * Used for the "Published Since" sort.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * URL path. Auto-filled from the title if left blank.
   */
  slug: string;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewerName: string;
  style?: ('quote' | 'featured') | null;
  /**
   * Star rating, 1–5.
   */
  rating?: number | null;
  /**
   * The review text.
   */
  quote?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * e.g. "CHOOSE YOUR".
   */
  headingLine1?: string | null;
  /**
   * Highlighted line, e.g. "HOME AWAY HOME".
   */
  headingLine2?: string | null;
  backgroundImage?: (number | null) | Media;
  /**
   * e.g. "BOOK NOW" or "RENT NOW".
   */
  ctaLabel?: string | null;
  ctaLink?: string | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips".
 */
export interface Tip {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional YouTube / clip link.
   */
  videoUrl?: string | null;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * Uncheck to hide from the site.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  company?: string | null;
  /**
   * The caravan/tour being enquired about.
   */
  destination?: string | null;
  preferredTravelDates?: string | null;
  groupSize?: string | null;
  budgetRange?: string | null;
  requirements?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'caravan-filter-options';
        value: number | CaravanFilterOption;
      } | null)
    | ({
        relationTo: 'tour-filter-options';
        value: number | TourFilterOption;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'caravans';
        value: number | Caravan;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'blog-articles';
        value: number | BlogArticle;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'tips';
        value: number | Tip;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  category?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravan-filter-options_select".
 */
export interface CaravanFilterOptionsSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-filter-options_select".
 */
export interface TourFilterOptionsSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravans_select".
 */
export interface CaravansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  sleeps?: T;
  chargesFrom?: T;
  baseVehicle?: T;
  baseLocation?: T;
  driveType?: T;
  berthRange?: T;
  class?: T;
  specifications?: T;
  additionalSpecifications?: T;
  uniqueFeatures?: T;
  additionalUniqueFeatures?: T;
  inclusions?: T;
  additionalInclusions?: T;
  exclusions?: T;
  additionalExclusions?: T;
  addOns?: T;
  additionalAddOns?: T;
  highlights?:
    | T
    | {
        label?: T;
        thumbnail?: T;
        videoUrl?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  durationLabel?: T;
  durationBand?: T;
  routeLabel?: T;
  location?: T;
  preference?: T;
  season?: T;
  itinerary?:
    | T
    | {
        dayTitle?: T;
        description?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        label?: T;
        thumbnail?: T;
        videoUrl?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  tales?: T;
  snaps?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles_select".
 */
export interface BlogArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  publishedAt?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  style?: T;
  rating?: T;
  quote?: T;
  photo?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  headingLine1?: T;
  headingLine2?: T;
  backgroundImage?: T;
  ctaLabel?: T;
  ctaLink?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips_select".
 */
export interface TipsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  videoUrl?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  destination?: T;
  preferredTravelDates?: T;
  groupSize?: T;
  budgetRange?: T;
  requirements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        /**
         * e.g. "Instagram", "Facebook".
         */
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  reviewsIntro?: {
    heading?: string | null;
    aboutBlurb?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  aboutSections?:
    | {
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        imageSide?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  footprint?:
    | {
        /**
         * e.g. "15+", "365 Days".
         */
        value: string;
        /**
         * e.g. "Trail Masters".
         */
        label?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  dreamBigCta?: {
    heading?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  backgroundImage?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subtext?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  reviewsIntro?:
    | T
    | {
        heading?: T;
        aboutBlurb?: T;
      };
  aboutSections?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        imageSide?: T;
        id?: T;
      };
  footprint?:
    | T
    | {
        value?: T;
        label?: T;
        caption?: T;
        id?: T;
      };
  dreamBigCta?:
    | T
    | {
        heading?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}