/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tours: Tour;
    caravans: Caravan;
    innovations: Innovation;
    'blog-articles': BlogArticle;
    galleries: Gallery;
    pages: Page;
    'hero-slides': HeroSlide;
    reviews: Review;
    tips: Tip;
    enquiries: Enquiry;
    subscribers: Subscriber;
    features: Feature;
    'caravan-filter-options': CaravanFilterOption;
    'tour-filter-options': TourFilterOption;
    'blog-categories': BlogCategory;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tours: ToursSelect<false> | ToursSelect<true>;
    caravans: CaravansSelect<false> | CaravansSelect<true>;
    innovations: InnovationsSelect<false> | InnovationsSelect<true>;
    'blog-articles': BlogArticlesSelect<false> | BlogArticlesSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    tips: TipsSelect<false> | TipsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'caravan-filter-options': CaravanFilterOptionsSelect<false> | CaravanFilterOptionsSelect<true>;
    'tour-filter-options': TourFilterOptionsSelect<false> | TourFilterOptionsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    business: Business;
    header: Header;
    footer: Footer;
    homepage: Homepage;
    about: About;
    'video-showcase': VideoShowcase;
  };
  globalsSelect: {
    business: BusinessSelect<false> | BusinessSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'video-showcase': VideoShowcaseSelect<false> | VideoShowcaseSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Your tour packages. Tick "Featured" to show a tour on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  name: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Theme badge shown on the tour card.
   */
  category?: ('Adventure' | 'Wildlife' | 'Nature' | 'Cultural' | 'Spiritual' | 'Beach') | null;
  /**
   * One or two lines shown on the tour card.
   */
  shortDescription?: string | null;
  /**
   * The text on the tour page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the card, e.g. "15 Days".
   */
  durationLabel?: string | null;
  durationBand?: (number | null) | TourFilterOption;
  /**
   * e.g. "Delhi – Ladakh – Delhi".
   */
  routeLabel?: string | null;
  location?: (number | null) | TourFilterOption;
  preference?: (number | TourFilterOption)[] | null;
  /**
   * e.g. "May – September".
   */
  season?: string | null;
  itinerary?:
    | {
        /**
         * e.g. "Day 1: Delhi → Corbett".
         */
        dayTitle: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        /**
         * e.g. "Fun Activities".
         */
        label: string;
        thumbnail?: (number | null) | Media;
        /**
         * YouTube link or short clip URL.
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Text on the booking buttons of this tour.
   */
  ctaLabel?: string | null;
  ctaLink?: string | null;
  tales?: (number | null) | BlogArticle;
  snaps?: (number | null) | Gallery;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every photo used on the website. Upload here, then pick it on any page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A few words about the photo, e.g. "Willow caravan at sunset in Ladakh". Helps Google and blind visitors.
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-filter-options".
 */
export interface TourFilterOption {
  id: number;
  /**
   * e.g. "Ladakh", "7–15 Days", "Riverside Caravanning".
   */
  name: string;
  group: 'duration-band' | 'location' | 'preference';
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles".
 */
export interface BlogArticle {
  id: number;
  title: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  coverImage?: (number | null) | Media;
  /**
   * Short summary for cards.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The "Featuring" tags for this article.
   */
  category?: (number | BlogCategory)[] | null;
  /**
   * Used for the "Published Since" sort.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photo albums shown on the Gallery page. Add photos to an album, then drag them to change the order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Your caravans. Tick the features each one has; only ticked ones show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravans".
 */
export interface Caravan {
  id: number;
  /**
   * The caravan's name, e.g. "Willow".
   */
  name: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * One or two lines — shown on the caravan's card in listings.
   */
  shortDescription?: string | null;
  /**
   * The full text under the photo on the caravan's page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as "Sleeps", e.g. "4–6 People".
   */
  sleeps?: string | null;
  /**
   * Shown as "Base vehicle", e.g. "Tata 4300 wb Chassis".
   */
  baseVehicle?: string | null;
  class?: (number | null) | CaravanFilterOption;
  driveType?: (number | null) | CaravanFilterOption;
  baseLocation?: (number | null) | CaravanFilterOption;
  berthRange?: (number | null) | CaravanFilterOption;
  specifications?: (number | Feature)[] | null;
  /**
   * Only for something this caravan has that is NOT in the tick-list above. Separate items with commas (e.g. "Solar panel, Roof deck"). Each one appears on the website just like a ticked item.
   */
  additionalSpecifications?: string | null;
  uniqueFeatures?: (number | Feature)[] | null;
  /**
   * Only for something this caravan has that is NOT in the tick-list above. Separate items with commas (e.g. "Solar panel, Roof deck"). Each one appears on the website just like a ticked item.
   */
  additionalUniqueFeatures?: string | null;
  inclusions?: (number | Feature)[] | null;
  /**
   * Only for something this caravan has that is NOT in the tick-list above. Separate items with commas (e.g. "Solar panel, Roof deck"). Each one appears on the website just like a ticked item.
   */
  additionalInclusions?: string | null;
  exclusions?: (number | Feature)[] | null;
  /**
   * Only for something this caravan has that is NOT in the tick-list above. Separate items with commas (e.g. "Solar panel, Roof deck"). Each one appears on the website just like a ticked item.
   */
  additionalExclusions?: string | null;
  addOns?: (number | Feature)[] | null;
  /**
   * Only for something this caravan has that is NOT in the tick-list above. Separate items with commas (e.g. "Solar panel, Roof deck"). Each one appears on the website just like a ticked item.
   */
  additionalAddOns?: string | null;
  /**
   * Questions & answers shown near the bottom of the caravan's page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Up to 3 YouTube walk-through / vlog links.
   */
  relatedVideos?:
    | {
        title?: string | null;
        /**
         * YouTube link or playlist URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Blog posts about this caravan — shown in the "Tales" tab.
   */
  relatedArticles?: (number | BlogArticle)[] | null;
  /**
   * Gallery albums from trips with this caravan — shown in the "Snaps" tab.
   */
  snaps?: (number | Gallery)[] | null;
  highlights?:
    | {
        label: string;
        thumbnail?: (number | null) | Media;
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  chargesFrom?: string | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravan-filter-options".
 */
export interface CaravanFilterOption {
  id: number;
  /**
   * e.g. "Delhi", "Chauffeur Driven", "8–12 Berth", "Zenith".
   */
  name: string;
  group: 'base-location' | 'drive-type' | 'berth-range' | 'class';
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The master list of features you can tick on each caravan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  name: string;
  /**
   * Icon shown next to this feature on the site.
   */
  icon: number | Media;
  category: 'spec' | 'inclusion' | 'exclusion' | 'unique-feature' | 'add-on';
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Specialised vehicles (arcade, lounger, vanity van...).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovations".
 */
export interface Innovation {
  id: number;
  name: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  /**
   * Badge, e.g. "Gaming", "Beauty".
   */
  category?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * One or two lines shown on the vehicle card.
   */
  shortDescription?: string | null;
  /**
   * The text on the vehicle page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "6".
   */
  seats?: string | null;
  /**
   * e.g. "6 people".
   */
  sleeps?: string | null;
  /**
   * e.g. "Delhi".
   */
  baseLocation?: string | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Extra pages like Terms, Privacy, FAQ. Each one lives at yoursite.com/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Filled in automatically from the name — leave it empty. Changing it later breaks old links to this page.
   */
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The big photo slideshow at the top of the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * e.g. "CHOOSE YOUR".
   */
  headingLine1?: string | null;
  /**
   * Highlighted line, e.g. "HOME AWAY HOME".
   */
  headingLine2?: string | null;
  /**
   * A wide landscape photo. Set its focus point in Media so phones crop it well.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * e.g. "BOOK NOW" or "RENT NOW".
   */
  ctaLabel?: string | null;
  /**
   * Where the button goes, e.g. /tours/the-adventures-of-ladakh or /caravans/willow.
   */
  ctaLink?: string | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer testimonials shown under the homepage slideshow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewerName: string;
  style?: ('quote' | 'featured') | null;
  /**
   * Star rating, 1–5.
   */
  rating?: number | null;
  /**
   * The review text.
   */
  quote?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The TIPS list on the homepage. Each tip opens to show its text (use bullet points like the others).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips".
 */
export interface Tip {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoUrl?: string | null;
  /**
   * Lower numbers show first (1, 2, 3…).
   */
  sortOrder?: number | null;
  /**
   * Tick to show it in its row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Untick to hide it from the website without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Booking requests sent from the website forms. Update the status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  /**
   * Where this lead stands.
   */
  status?: ('new' | 'contacted' | 'quoted' | 'booked' | 'closed') | null;
  /**
   * Private notes — never shown on the website.
   */
  notes?: string | null;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  company?: string | null;
  /**
   * What the visitor picked at the top of the form.
   */
  enquiryType?: ('tour' | 'caravan' | 'innovation') | null;
  /**
   * The tour, caravan or vehicle they chose (or "Not sure yet").
   */
  destination?: string | null;
  preferredTravelDates?: string | null;
  groupSize?: string | null;
  budgetRange?: string | null;
  requirements?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who joined the newsletter (Join The Caravan CLUB).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'caravans';
        value: number | Caravan;
      } | null)
    | ({
        relationTo: 'innovations';
        value: number | Innovation;
      } | null)
    | ({
        relationTo: 'blog-articles';
        value: number | BlogArticle;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'tips';
        value: number | Tip;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'caravan-filter-options';
        value: number | CaravanFilterOption;
      } | null)
    | ({
        relationTo: 'tour-filter-options';
        value: number | TourFilterOption;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  shortDescription?: T;
  description?: T;
  durationLabel?: T;
  durationBand?: T;
  routeLabel?: T;
  location?: T;
  preference?: T;
  season?: T;
  itinerary?:
    | T
    | {
        dayTitle?: T;
        description?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        label?: T;
        thumbnail?: T;
        videoUrl?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  tales?: T;
  snaps?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravans_select".
 */
export interface CaravansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  sleeps?: T;
  baseVehicle?: T;
  class?: T;
  driveType?: T;
  baseLocation?: T;
  berthRange?: T;
  specifications?: T;
  additionalSpecifications?: T;
  uniqueFeatures?: T;
  additionalUniqueFeatures?: T;
  inclusions?: T;
  additionalInclusions?: T;
  exclusions?: T;
  additionalExclusions?: T;
  addOns?: T;
  additionalAddOns?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedVideos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  relatedArticles?: T;
  snaps?: T;
  highlights?:
    | T
    | {
        label?: T;
        thumbnail?: T;
        videoUrl?: T;
        id?: T;
      };
  chargesFrom?: T;
  ctaLabel?: T;
  ctaLink?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovations_select".
 */
export interface InnovationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  seats?: T;
  sleeps?: T;
  baseLocation?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles_select".
 */
export interface BlogArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  publishedAt?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  sortOrder?: T;
  featured?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  headingLine1?: T;
  headingLine2?: T;
  backgroundImage?: T;
  ctaLabel?: T;
  ctaLink?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  style?: T;
  rating?: T;
  quote?: T;
  photo?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips_select".
 */
export interface TipsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  videoUrl?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  status?: T;
  notes?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  enquiryType?: T;
  destination?: T;
  preferredTravelDates?: T;
  groupSize?: T;
  budgetRange?: T;
  requirements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  category?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caravan-filter-options_select".
 */
export interface CaravanFilterOptionsSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-filter-options_select".
 */
export interface TourFilterOptionsSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details shown across the website. Change them here and they update everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business".
 */
export interface Business {
  id: number;
  /**
   * Shown in the footer and contact page, e.g. "+91 98710 63984".
   */
  phone?: string | null;
  /**
   * Number with country code, digits only (e.g. 919871063984). Powers the green chat button. Leave empty to hide it.
   */
  whatsapp?: string | null;
  email?: string | null;
  /**
   * Office / garage address.
   */
  address?: string | null;
  mapUrl?: string | null;
  /**
   * e.g. "Mon–Sat, 10am–7pm".
   */
  hours?: string | null;
  /**
   * Every new booking enquiry is emailed here (once email sending is set up).
   */
  enquiryNotifyEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        /**
         * A page on this site, e.g. /tours, or a full web address starting with https://
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              /**
               * e.g. /privacy-policy, or a full web address starting with https://
               */
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        /**
         * e.g. "Instagram", "Facebook".
         */
        platform: string;
        /**
         * The full address of your page, e.g. https://www.instagram.com/…
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Our Story (the chapters with the year), Our Footprint (the three arches) and the Dream Big banner. The slideshow, reviews and tips have their own sections in this menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  reviewsIntro?: {
    heading?: string | null;
    aboutBlurb?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * The story chapters, in order. Drag to reorder; the first one opens the section.
   */
  aboutSections?:
    | {
        /**
         * Shown as the big outlined year above the heading in "Our Story", e.g. "1993".
         */
        year?: string | null;
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        /**
         * Paste a YouTube link — the video plays here instead of the photo (muted, on loop; visitors can turn the sound on).
         */
        video?: string | null;
        imageSide?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The three arches. In every text, " · " starts a new line (e.g. "India · Nepal · Bhutan · Tibet"). A short big text like "15+" is shown extra large.
   */
  footprint?:
    | {
        /**
         * e.g. "1 Day Trip · Or".
         */
        intro?: string | null;
        /**
         * e.g. "15+", "365 Days".
         */
        value: string;
        /**
         * e.g. "Years · Driver & Helper · Experience".
         */
        caption?: string | null;
        /**
         * e.g. "Trail Masters".
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The "Dream Big With Us" banner: a heading and two buttons (design page 39). Leave a button's text empty to hide it.
   */
  dreamBigCta?: {
    heading?: string | null;
    ctaLabel?: string | null;
    /**
     * e.g. /blog/… or /about
     */
    ctaLink?: string | null;
    secondCtaLabel?: string | null;
    /**
     * e.g. /blog/… or /contact
     */
    secondCtaLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  headline?: string | null;
  /**
   * The opening story / who we are.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional intro video or photo.
   */
  video?: (number | null) | Media;
  team?:
    | {
        name: string;
        /**
         * e.g. "Founder", "Head Driver".
         */
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  hiring?: {
    heading?: string | null;
    /**
     * A line about working with the team.
     */
    text?: string | null;
    ctaLabel?: string | null;
    /**
     * Link to your LinkedIn hiring section.
     */
    ctaLink?: string | null;
  };
  /**
   * Instagram profile URL.
   */
  instagramUrl?: string | null;
  /**
   * YouTube channel URL.
   */
  youtubeUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The row of videos shown on every page except the homepage (tours, caravans, innovations, blog, gallery…). Empty = the row is hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-showcase".
 */
export interface VideoShowcase {
  id: number;
  /**
   * Optional title above the videos, e.g. "Life on the road". Leave empty for none.
   */
  heading?: string | null;
  /**
   * Drag to change the order. Mix tall (Shorts) and wide videos, as on the design.
   */
  videos?:
    | {
        /**
         * Paste the link from YouTube — a normal video or a Short.
         */
        url: string;
        /**
         * Optional, shown on the tile.
         */
        title?: string | null;
        shape?: ('auto' | 'tall' | 'wide') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_select".
 */
export interface BusinessSelect<T extends boolean = true> {
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  mapUrl?: T;
  hours?: T;
  enquiryNotifyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  backgroundImage?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subtext?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  reviewsIntro?:
    | T
    | {
        heading?: T;
        aboutBlurb?: T;
      };
  aboutSections?:
    | T
    | {
        year?: T;
        heading?: T;
        body?: T;
        image?: T;
        video?: T;
        imageSide?: T;
        id?: T;
      };
  footprint?:
    | T
    | {
        intro?: T;
        value?: T;
        caption?: T;
        label?: T;
        id?: T;
      };
  dreamBigCta?:
    | T
    | {
        heading?: T;
        ctaLabel?: T;
        ctaLink?: T;
        secondCtaLabel?: T;
        secondCtaLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  video?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  hiring?:
    | T
    | {
        heading?: T;
        text?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  instagramUrl?: T;
  youtubeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-showcase_select".
 */
export interface VideoShowcaseSelect<T extends boolean = true> {
  heading?: T;
  videos?:
    | T
    | {
        url?: T;
        title?: T;
        shape?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}